name: CI/CD Pipeline - Langflow to ECS Fargate

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}   # Full ECR repo URI, e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/langflow
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}       # Just the registry, e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_TAG: latest

jobs:
  deploy:
    name: Build, Push to ECR, Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install CDK Dependencies
        working-directory: infra  
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Set Docker builder to classic
        run: docker buildx stop || true

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
          --platform linux/amd64 \
          --tag $ECR_REPOSITORY:$IMAGE_TAG \
          --push langflow


      - name: CDK Bootstrap
        working-directory: infra
        run: cdk bootstrap

      - name: CDK Deploy
        working-directory: infra
        run: cdk deploy --require-approval never
